id: 36444f5c1ed8465f980ebc8868ecd82e
initial_creation_type: ocr
source_metadata:
  volumes:
    f174c340be2b48508ccc99ebd593053d:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: ''
      total_pages: 1586
      volume_number: 24
